sonar.projectKey=barbershop-devops
sonar.projectName=Barbershop DevOps
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
